export interface Project {
  id: string;
  num: string;
  title: string;
  category: string;
  description: string;
  featured: boolean;
  date: string;
  slug: string;
  image?: string;
}

export const projects: Project[] = [
  // Featured Projects
  {
    id: "9th-ward",
    num: "01",
    title: "9th Ward Stabilization Project",
    category: "SPATIAL ANALYSIS",
    description: "A comprehensive spatial strategy analyzing vacant property distribution and community stabilization patterns in New Orleans' 9th Ward.",
    featured: true,
    date: "2023",
    slug: "9th-ward-stabilization",
    image: "/images/projects/9th-ward-stabilization.jpg",
  },
  {
    id: "eastside",
    num: "02",
    title: "Eastside Friendly Property Renovation",
    category: "WEB GIS",
    description: "Interactive ArcGIS Experience Builder application showcasing before-and-after rendering effects for property renovation projects.",
    featured: true,
    date: "2024",
    slug: "eastside-renovation",
    image: "/images/projects/eastside-renovation.jpg",
  },
  {
    id: "river-road",
    num: "03",
    title: "Minnesota Great River Road Travel Guide",
    category: "Esri StoryMap",
    description: "Award-winning Esri StoryMap documenting the Mississippi River exploration experience with video, 360-degree photography, and historical context.",
    featured: true,
    date: "2021",
    slug: "river-road-travel-guide",
    image: "/images/projects/river-road-travel-guide.jpg",
  },

  // Archive Projects
  {
    id: "japan-earthquake",
    num: "01",
    title: "Japan Earthquake Animation",
    category: "Visualization",
    description: "Animating movement and distribution of seismic activity in Japan with temporal analysis.",
    featured: false,
    date: "2017",
    slug: "japan-earthquake-animation",
    image: "https://images.unsplash.com/photo-1585229045563-ef7e17dd286b?w=800&h=600&fit=crop",
  },
  {
    id: "traffic-flow",
    num: "02",
    title: "Traffic Flow Hennepin County",
    category: "Transportation",
    description: "Interactive visualization of traffic patterns and flow analysis across Hennepin County using real-time data.",
    featured: false,
    date: "2018",
    slug: "traffic-flow-hennepin",
    image: "https://images.unsplash.com/photo-1687657280574-011186d45d41?w=800&h=600&fit=crop",
  },
  {
    id: "watershed",
    num: "04",
    title: "Watershed Delineation & Flood Risk Mapping",
    category: "Hydrology",
    description: "Advanced spatial analysis for watershed delineation and modeling flood risk zones using hydrological modeling.",
    featured: false,
    date: "2020",
    slug: "plan-your-trip",
    image: "https://images.unsplash.com/photo-1579033100692-c247a7c6e4dc?w=800&h=600&fit=crop",
  },
  {
    id: "police-violence",
    num: "05",
    title: "Police Violence Visualization",
    category: "Social Justice",
    description: "Spatial analysis and visualization of police incidents with temporal trends and geographic patterns.",
    featured: false,
    date: "2020",
    slug: "police-violence-visualization",
    image: "https://images.unsplash.com/photo-1633356122544-f134324ef6db?w=800&h=600&fit=crop",
  },
  {
    id: "pokemon-go",
    num: "06",
    title: "Pokémon GO at UMN",
    category: "Interactive Map",
    description: "Geospatial analysis of location-based gaming adoption patterns across the University of Minnesota campus.",
    featured: false,
    date: "2016",
    slug: "pokemon-go-umn",
    image: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=800&h=600&fit=crop",
  },
  {
    id: "zoning-analysis",
    num: "07",
    title: "Zoning Buffer Analysis",
    category: "Urban Planning",
    description: "Comprehensive GIS analysis of zoning regulations and buffer zone impacts on urban development.",
    featured: false,
    date: "2018",
    slug: "zoning-buffer-analysis",
    image: "https://images.unsplash.com/photo-1604537529428-15bcbd7ae90e?w=800&h=600&fit=crop",
  },
  {
    id: "bennett-street",
    num: "08",
    title: "Bennett Street Plan",
    category: "Urban Design",
    description: "Strategic urban design and spatial planning project for neighborhood revitalization and streetscape improvement.",
    featured: false,
    date: "2019",
    slug: "bennett-street-plan",
    image: "https://images.unsplash.com/photo-1576721331346-e55f31a6f76a?w=800&h=600&fit=crop",
  },
  {
    id: "apple-watch",
    num: "09",
    title: "Apple Watch Exercise App Animation",
    category: "UI Animation",
    description: "High-fidelity animation design for a fitness wearable application.",
    featured: false,
    date: "2018",
    slug: "apple-watch-animation",
    image: "/images/projects/apple-watch-animation.jpg",
  },
  {
    id: "barn-swallows",
    num: "10",
    title: "Argentine Barn Swallows Migration",
    category: "Geovisualization",
    description: "Visualizing long-distance range expansion and rapid adjustment of migration in swallow populations.",
    featured: false,
    date: "2022",
    slug: "barn-swallows-geovisualization",
    image: "/images/projects/barn-swallows-geovisualization.jpg",
  },
  {
    id: "blight-wilmington",
    num: "11",
    title: "Blight & Vacants in Wilmington",
    category: "Data Visualization",
    description: "Visualizing urban decay using ArcGIS Online Dashboard for metropolitan decision-making.",
    featured: true,
    date: "2024",
    slug: "blight-vacants-wilmington",
    image: "/images/projects/blight-vacants-wilmington.jpg",
  },
  {
    id: "museum-app",
    num: "12",
    title: "Museum App Prototype",
    category: "UI/UX",
    description: "Designing the textile art exhibit mobile app for Cooper Hewitt Museum.",
    featured: false,
    date: "2019",
    slug: "museum-app-prototype",
    image: "/images/projects/museum-app-prototype.jpg",
  },
  {
    id: "plan-project",
    num: "13",
    title: "Plan Your Project Map Tool",
    category: "Web Mapping",
    description: "Harnessing GIS for multi-modal travel coordination and transportation planning.",
    featured: false,
    date: "2020",
    slug: "plan-your-project",
    image: "/images/projects/plan-your-project.jpg",
  },
  {
    id: "student-distribution",
    num: "14",
    title: "Student Distribution Around UMN",
    category: "Spatial Analysis",
    description: "Examining spatial relationships between student housing, rental prices, and ethnicity.",
    featured: false,
    date: "2016",
    slug: "student-distribution-umn",
    image: "/images/projects/student-distribution-umn.jpg",
  },
];

export const featuredProjects = projects.filter(p => p.featured);
export const archiveProjects = projects.filter(p => !p.featured);
